import { resolve } from "node:path";
import type { Page } from "@playwright/test";
import { expect, test } from "../../fixtures/test";
import { discardNode } from "../../helpers/drive";
import {
	createWriterDocument,
	documentMenuButton,
	openWriterDocument,
	uniqueWriterTitle,
	writerEditor,
} from "../../helpers/writer";

// Generated by frappe-ui's own "docx" package: one heading, one paragraph, and
// a 2-row table with the first row flagged as a header.
const fixturePath = resolve(__dirname, "fixtures/import-sample.docx");

async function importDocx(page: Page) {
	const [fileChooser] = await Promise.all([
		page.waitForEvent("filechooser"),
		(async () => {
			await documentMenuButton(page).click();
			await page.getByRole("menuitem", { name: "Import DOCX" }).click();
		})(),
	]);
	await fileChooser.setFiles(fixturePath);
}

test("imports a .docx into an empty document", async ({ owner, run }) => {
	const file = await createWriterDocument(
		owner.page.request,
		uniqueWriterTitle(run.run_id, "docx-import-empty"),
	);
	await openWriterDocument(owner.page, file.name);

	await importDocx(owner.page);

	const editor = writerEditor(owner.page);
	await expect(editor).toContainText("E2E DOCX Import Fixture");
	await expect(editor).toContainText("This paragraph was imported from a .docx file.");
	await expect(editor.locator("table")).toBeVisible();
	await expect(editor.locator("th", { hasText: "Fruit" })).toBeVisible();
	await expect(editor.locator("td", { hasText: "Apple" })).toBeVisible();
	// Only the first row is a header, matching a manually created table.
	await expect(editor.locator("th")).toHaveCount(2);

	await discardNode(owner.page.request, file.name);
});

test("imports a .docx into a new tab, leaving existing content untouched", async ({
	owner,
	run,
}) => {
	const file = await createWriterDocument(
		owner.page.request,
		uniqueWriterTitle(run.run_id, "docx-import-tab"),
	);
	// The tab switcher lives in the desktop Table of Contents panel.
	await owner.page.addInitScript(() => window.localStorage.setItem("showToc", "true"));
	await openWriterDocument(owner.page, file.name);

	const editor = writerEditor(owner.page);
	await editor.click();
	await owner.page.keyboard.type("Existing content before import");

	await importDocx(owner.page);

	// The existing content stays as the first ("Untitled") tab and the imported
	// content opens in a new tab named after the file. Inactive tabs stay in the
	// DOM hidden, so assertions read the rendered text only.
	const tocTabs = owner.page.locator('[draggable="true"]');
	await expect(tocTabs).toHaveText(["Untitled", "import-sample"]);
	await expect(editor).toContainText("E2E DOCX Import Fixture", { useInnerText: true });
	await expect(editor).not.toContainText("Existing content before import", {
		useInnerText: true,
	});

	await tocTabs.filter({ hasText: "Untitled" }).click();
	await expect(editor).toContainText("Existing content before import", { useInnerText: true });
	await expect(editor).not.toContainText("E2E DOCX Import Fixture", { useInnerText: true });

	await discardNode(owner.page.request, file.name);
});
