// Regenerates coverage.md from the corpus. Run from this directory:
//
//   node report.mjs > coverage.md
//
// The table is generated rather than hand-maintained so it cannot drift from
// the fixtures. A function with no fixture is a gap, and this is what surfaces
// it.

import { readdirSync, readFileSync, statSync } from "node:fs"
import { join } from "node:path"

import { getFunctionNames } from "../formula.js"

function walk(dir) {
	return readdirSync(dir).flatMap((name) => {
		const p = join(dir, name)
		return statSync(p).isDirectory() ? walk(p) : p.endsWith(".json") ? [p] : []
	})
}

const cases = []
for (const file of walk(".")) {
	const doc = JSON.parse(readFileSync(file, "utf8"))
	const list = Array.isArray(doc) ? doc : doc.cases
	if (Array.isArray(list)) for (const c of list) cases.push({ ...c, file })
}

const known = cases.filter((c) => c.status === "known-failure")

// A fixture counts towards a function when it calls it. Matching on the call
// shape (`NAME(`) avoids crediting SUM for a fixture that merely mentions it.
function usesFunction(text, fn) {
	return new RegExp(`\\b${fn}\\s*\\(`, "i").test(text)
}

const DIMENSIONS = [
	// A dimension is covered when at least one fixture for that function looks
	// like it. These are heuristics over the corpus, not a substitute for the
	// per-agent coverage tables in the reports.
	["Basic", () => true],
	["Args", (c) => /argument|arity|missing|extra|too few|too many/i.test(`${c.category} ${c.notes ?? ""}`)],
	["Types", (c) => /coercion|type|text|boolean|blank/i.test(`${c.category} ${c.notes ?? ""}`)],
	["Errors", (c) => typeof c.expected === "string" && c.expected.startsWith("#")],
	["Bounds", (c) => /boundary|bound|overflow|limit|negative|zero|empty/i.test(`${c.category} ${c.notes ?? ""}`)],
]

const rows = []
for (const fn of getFunctionNames()) {
	const mine = cases.filter((c) => c.formula && usesFunction(c.formula, fn))
	const failing = mine.filter((c) => c.status === "known-failure").length
	rows.push({
		fn,
		total: mine.length,
		failing,
		marks: DIMENSIONS.map(([, test]) => (mine.some(test) ? "y" : "-")),
	})
}

const untested = rows.filter((r) => r.total === 0)
const byDefect = {}
for (const c of known) byDefect[c.defect ?? "unclassified"] = (byDefect[c.defect ?? "unclassified"] ?? 0) + 1

const out = []
out.push("# Formula engine coverage")
out.push("")
out.push("Generated by `node report.mjs > coverage.md`. Do not edit by hand.")
out.push("")
out.push(`- Fixtures: **${cases.length}**`)
out.push(`- Matching the spreadsheet today: **${cases.length - known.length}**`)
out.push(`- Recorded defects (\`known-failure\`): **${known.length}**`)
out.push(`- Built-in functions: **${rows.length}**`)
out.push(`- Functions with no fixture: **${untested.length}**`)
out.push("")
out.push("## Defects by class")
out.push("")
out.push("| Class | Fixtures |")
out.push("| --- | --- |")
for (const [k, v] of Object.entries(byDefect).sort((a, b) => b[1] - a[1])) out.push(`| \`${k}\` | ${v} |`)
out.push("")
out.push("## Functions")
out.push("")
out.push(`| Function | Fixtures | Failing | ${DIMENSIONS.map((d) => d[0]).join(" | ")} |`)
out.push(`| --- | --- | --- | ${DIMENSIONS.map(() => "---").join(" | ")} |`)
for (const r of rows) {
	out.push(`| ${r.fn} | ${r.total} | ${r.failing} | ${r.marks.join(" | ")} |`)
}
if (untested.length) {
	out.push("")
	out.push("## Functions with no fixture")
	out.push("")
	out.push(untested.map((r) => r.fn).join(", "))
}

console.log(out.join("\n"))
