name: Client CI

on:
  push:
    branches:
      - develop
    paths:
      - "suite/client/**"
      - "suite/calendar/**"
      - "frontend/src/apps/calendar/**"
      - "pyproject.toml"
      - ".github/workflows/client-ci.yml"
      - ".github/workflows/suite-module-ci.yml"
  pull_request:
    paths:
      - "suite/client/**"
      - "suite/calendar/**"
      - "frontend/src/apps/calendar/**"
      - "pyproject.toml"
      - ".github/workflows/client-ci.yml"
      - ".github/workflows/suite-module-ci.yml"
  workflow_dispatch:

concurrency:
  group: client-ci-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  server:
    uses: ./.github/workflows/suite-module-ci.yml
    with:
      module: suite.client
      test-path: suite/client
