name: Drive CI

on:
  push:
    branches:
      - develop
    paths:
      - "suite/drive/**"
      - "frontend/src/apps/drive/**"
      - "pyproject.toml"
      - ".github/workflows/drive-ci.yml"
      - ".github/workflows/suite-module-ci.yml"
  pull_request:
    paths:
      - "suite/drive/**"
      - "frontend/src/apps/drive/**"
      - "pyproject.toml"
      - ".github/workflows/drive-ci.yml"
      - ".github/workflows/suite-module-ci.yml"
  workflow_dispatch:

concurrency:
  group: drive-ci-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  backend-frontend:
    uses: ./.github/workflows/suite-module-ci.yml
    with:
      module: suite.drive
      test-path: suite/drive
